"""Authoritative per-question technique tags (kebab-case)."""

# Per-question authoritative tags (technique-focused, kebab-case).
QUESTION_TAGS = {
    # Arrays & Hashing
    "Two Sum": ["hashmap"],
    "Contains Duplicate": ["hashmap"],
    "Contains Duplicate II": ["hashmap", "sliding-window"],
    "Valid Anagram": ["hashmap"],
    "Group Anagrams": ["hashmap"],
    "Top K Frequent Elements": ["hashmap", "heap"],
    "Product of Array Except Self": ["prefix-sum"],
    "Longest Consecutive Sequence": ["hashmap"],
    "Encode and Decode Strings": ["string"],
    "Find the Duplicate Number": ["floyd-cycle", "hashmap"],
    "First Unique Character in a String": ["hashmap"],
    "Ransom Note": ["hashmap"],
    "Isomorphic Strings": ["hashmap"],
    "Word Pattern": ["hashmap"],
    "Happy Number": ["hashmap"],
    "Intersection of Two Arrays": ["hashmap"],
    "Intersection of Two Arrays II": ["hashmap"],
    "Find All Numbers Disappeared in an Array": ["hashmap"],
    "Set Mismatch": ["hashmap"],
    "Majority Element": ["hashmap"],
    "Sort Colors": ["two-pointers"],
    "Move Zeroes": ["two-pointers"],
    "Remove Element": ["two-pointers"],
    "Remove Duplicates from Sorted Array": ["two-pointers"],
    "Remove Duplicates from Sorted Array II": ["two-pointers"],
    "Merge Sorted Array": ["two-pointers"],
    "Rotate Array": ["array"],
    "Jump Game": ["greedy"],
    "Jump Game II": ["greedy"],
    "Gas Station": ["greedy"],
    "Candy": ["greedy"],
    "H-Index": ["sorting"],
    "Relative Ranks": ["heap"],
    "Third Maximum Number": ["sorting"],
    "Max Consecutive Ones": ["array"],
    "Longest Harmonious Subsequence": ["hashmap", "sorting"],
    "Longest Palindrome": ["hashmap"],
    "Pascal's Triangle": ["array"],
    "Pascal's Triangle II": ["array"],
    "Array Partition": ["greedy", "sorting"],
    "Distribute Candies": ["hashmap"],
    "Minimum Index Sum of Two Lists": ["hashmap"],
    "Keyboard Row": ["hashmap"],
    "Longest Common Prefix": ["string"],
    "Find the Index of the First Occurrence in a String": ["string"],
    "Reverse Words in a String": ["string"],
    "Length of Last Word": ["string"],
    "Number of Segments in a String": ["string"],
    "Detect Capital": ["string"],
    "License Key Formatting": ["string"],
    "Repeated Substring Pattern": ["string"],
    "Reverse String II": ["string"],
    "String to Integer (atoi)": ["string"],
    "Student Attendance Record I": ["string"],
    "Longest Uncommon Subsequence I": ["string"],
    "Integer to Roman": ["math", "string"],
    "Roman to Integer": ["math", "string"],
    "Text Justification": ["string"],
    "Zigzag Conversion": ["string"],
    # Sliding Window
    "Longest Substring Without Repeating Characters": ["sliding-window"],
    "Longest Repeating Character Replacement": ["sliding-window"],
    "Minimum Window Substring": ["sliding-window"],
    "Minimum Size Subarray Sum": ["sliding-window"],
    "Find All Anagrams in a String": ["sliding-window"],
    "Permutation in String": ["sliding-window"],
    "Maximum Average Subarray I": ["sliding-window"],
    "Sliding Window Maximum": ["sliding-window", "monotonic-queue"],
    "Substring with Concatenation of All Words": ["sliding-window", "hashmap"],
    # Two Pointers
    "3Sum": ["two-pointers", "sorting"],
    "Container With Most Water": ["two-pointers"],
    "Trapping Rain Water": ["two-pointers"],
    "Two Sum II - Input Array Is Sorted": ["two-pointers"],
    "Valid Palindrome": ["two-pointers"],
    "Is Subsequence": ["two-pointers"],
    "Reverse String": ["two-pointers"],
    "Reverse Vowels of a String": ["two-pointers"],
    "Reverse Words in a String III": ["two-pointers"],
    # Binary Search
    "Binary Search": ["binary-search"],
    "Search Insert Position": ["binary-search"],
    "Find First and Last Position of Element in Sorted Array": ["binary-search"],
    "Search in Rotated Sorted Array": ["binary-search"],
    "Find Minimum in Rotated Sorted Array": ["binary-search"],
    "Search a 2D Matrix": ["binary-search"],
    "Find Peak Element": ["binary-search"],
    "Guess Number Higher or Lower": ["binary-search"],
    "First Bad Version": ["binary-search"],
    "Valid Perfect Square": ["binary-search"],
    "Arranging Coins": ["binary-search", "math"],
    "Koko Eating Bananas": ["binary-search"],
    "Median of Two Sorted Arrays": ["binary-search"],
    # Linked List
    "Reverse Linked List": ["linked-list"],
    "Merge Two Sorted Lists": ["linked-list"],
    "Linked List Cycle": ["floyd-cycle", "linked-list"],
    "Remove Nth Node From End of List": ["linked-list", "two-pointers"],
    "Add Two Numbers": ["linked-list"],
    "Copy List with Random Pointer": ["linked-list", "hashmap"],
    "Intersection of Two Linked Lists": ["linked-list", "two-pointers"],
    "Palindrome Linked List": ["linked-list", "two-pointers"],
    "Remove Linked List Elements": ["linked-list"],
    "Middle of the Linked List": ["linked-list", "two-pointers"],
    "Remove Duplicates from Sorted List": ["linked-list"],
    "Remove Duplicates from Sorted List II": ["linked-list"],
    "Rotate List": ["linked-list", "two-pointers"],
    "Partition List": ["linked-list", "two-pointers"],
    "Reorder List": ["linked-list", "two-pointers"],
    "Reverse Linked List II": ["linked-list"],
    "Reverse Nodes in k-Group": ["linked-list"],
    # Trees
    "Invert Binary Tree": ["tree-dfs"],
    "Maximum Depth of Binary Tree": ["tree-dfs"],
    "Same Tree": ["tree-dfs"],
    "Subtree of Another Tree": ["tree-dfs"],
    "Symmetric Tree": ["tree-dfs"],
    "Balanced Binary Tree": ["tree-dfs"],
    "Minimum Depth of Binary Tree": ["tree-dfs", "tree-bfs"],
    "Path Sum": ["tree-dfs"],
    "Sum Root to Leaf Numbers": ["tree-dfs"],
    "Binary Tree Paths": ["tree-dfs", "backtracking"],
    "Sum of Left Leaves": ["tree-dfs"],
    "Diameter of Binary Tree": ["tree-dfs"],
    "Count Good Nodes in Binary Tree": ["tree-dfs"],
    "Binary Tree Tilt": ["tree-dfs"],
    "Construct String from Binary Tree": ["tree-dfs"],
    "Binary Tree Inorder Traversal": ["tree-dfs"],
    "Binary Tree Preorder Traversal": ["tree-dfs"],
    "Binary Tree Postorder Traversal": ["tree-dfs"],
    "Lowest Common Ancestor of a Binary Tree": ["tree-dfs"],
    "Binary Tree Maximum Path Sum": ["tree-dfs"],
    "Construct Binary Tree from Preorder and Inorder Traversal": ["tree-dfs"],
    "Construct Binary Tree from Inorder and Postorder Traversal": ["tree-dfs"],
    "Flatten Binary Tree to Linked List": ["tree-dfs"],
    "Count Complete Tree Nodes": ["tree-dfs", "binary-search"],
    "Merge Two Binary Trees": ["tree-dfs"],
    "Populating Next Right Pointers in Each Node II": ["tree-bfs"],
    "Binary Tree Level Order Traversal": ["tree-bfs"],
    "Binary Tree Zigzag Level Order Traversal": ["tree-bfs"],
    "Binary Tree Right Side View": ["tree-bfs"],
    "Average of Levels in Binary Tree": ["tree-bfs"],
    "Validate Binary Search Tree": ["bst", "tree-dfs"],
    "Kth Smallest Element in a BST": ["bst", "tree-dfs"],
    "Lowest Common Ancestor of a Binary Search Tree": ["bst"],
    "Minimum Absolute Difference in BST": ["bst", "tree-dfs"],
    "Find Mode in Binary Search Tree": ["bst", "tree-dfs"],
    "Binary Search Tree Iterator": ["bst", "stack"],
    "Two Sum IV - Input is a BST": ["bst", "hashmap"],
    # Heap
    "Kth Largest Element in an Array": ["heap"],
    "Kth Largest Element in a Stream": ["heap"],
    "Last Stone Weight": ["heap"],
    "K Closest Points to Origin": ["heap"],
    "Task Scheduler": ["heap", "greedy"],
    "Find K Pairs with Smallest Sums": ["heap"],
    "Merge k Sorted Lists": ["heap", "divide-and-conquer", "linked-list"],
    "IPO": ["heap", "greedy"],
    # Backtracking
    "Subsets": ["backtracking"],
    "Subsets II": ["backtracking"],
    "Combinations": ["backtracking"],
    "Combination Sum": ["backtracking"],
    "Combination Sum II": ["backtracking"],
    "Permutations": ["backtracking"],
    "Generate Parentheses": ["backtracking"],
    "Letter Combinations of a Phone Number": ["backtracking"],
    "Palindrome Partitioning": ["backtracking"],
    "Word Search": ["backtracking", "matrix", "dfs"],
    "N-Queens": ["backtracking"],
    "N-Queens II": ["backtracking"],
    "Binary Watch": ["backtracking", "bit-manipulation"],
    # Tries
    "Implement Trie (Prefix Tree)": ["trie"],
    "Design Add and Search Words Data Structure": ["trie", "design"],
    "Word Search II": ["trie", "backtracking", "matrix"],
    # Graphs
    "Number of Islands": ["dfs", "matrix"],
    "Max Area of Island": ["dfs", "matrix"],
    "Flood Fill": ["dfs", "matrix"],
    "Surrounded Regions": ["dfs", "matrix"],
    "Pacific Atlantic Water Flow": ["dfs", "matrix"],
    "Clone Graph": ["dfs", "graph"],
    "Course Schedule": ["topological-sort", "dfs"],
    "Course Schedule II": ["topological-sort", "dfs"],
    "Evaluate Division": ["union-find", "graph"],
    "Number of Connected Components in an Undirected Graph": ["union-find"],
    "Graph Valid Tree": ["union-find", "graph"],
    "Redundant Connection": ["union-find"],
    "Accounts Merge": ["union-find", "graph"],
    "Rotting Oranges": ["bfs", "matrix"],
    "01 Matrix": ["bfs", "matrix"],
    "Walls and Gates": ["bfs", "matrix"],
    "Word Ladder": ["bfs"],
    "Snakes and Ladders": ["bfs"],
    "Minimum Genetic Mutation": ["bfs"],
    "Network Delay Time": ["dijkstra", "graph"],
    "Cheapest Flights Within K Stops": ["dijkstra", "graph"],
    "Min Cost to Connect All Points": ["minimum-spanning-tree", "graph"],
    "Swim in Rising Water": ["union-find", "binary-search", "graph"],
    "Alien Dictionary": ["topological-sort", "graph"],
    "Reconstruct Itinerary": ["dfs", "graph", "eulerian-path"],
    "Minimum Height Trees": ["bfs", "graph"],
    "Island Perimeter": ["matrix", "graph"],
    # Dynamic Programming
    "Climbing Stairs": ["1d-dp"],
    "Min Cost Climbing Stairs": ["1d-dp"],
    "Fibonacci Number": ["1d-dp"],
    "House Robber": ["1d-dp"],
    "House Robber II": ["1d-dp"],
    "Coin Change": ["1d-dp"],
    "Word Break": ["1d-dp"],
    "Longest Increasing Subsequence": ["1d-dp", "binary-search"],
    "Combination Sum IV": ["1d-dp"],
    "Decode Ways": ["1d-dp"],
    "Maximum Product Subarray": ["1d-dp"],
    "Palindromic Substrings": ["1d-dp"],
    "Partition Equal Subset Sum": ["1d-dp"],
    "Target Sum": ["1d-dp"],
    "Best Time to Buy and Sell Stock": ["1d-dp"],
    "Best Time to Buy and Sell Stock II": ["1d-dp", "greedy"],
    "Maximum Subarray": ["1d-dp", "kadane"],
    "Maximum Sum Circular Subarray": ["1d-dp", "kadane"],
    "Longest Common Subsequence": ["2d-dp"],
    "Edit Distance": ["2d-dp"],
    "Distinct Subsequences": ["2d-dp"],
    "Unique Paths": ["2d-dp"],
    "Unique Paths II": ["2d-dp"],
    "Minimum Path Sum": ["2d-dp", "matrix"],
    "Maximal Square": ["2d-dp", "matrix"],
    "Coin Change II": ["2d-dp"],
    "Regular Expression Matching": ["2d-dp"],
    "Interleaving String": ["2d-dp"],
    "Longest Increasing Path in a Matrix": ["2d-dp", "dfs", "matrix"],
    "Burst Balloons": ["2d-dp"],
    "Best Time to Buy and Sell Stock with Cooldown": ["2d-dp"],
    "Longest Palindromic Substring": ["2d-dp", "string"],
    "Best Time to Buy and Sell Stock III": ["2d-dp"],
    "Best Time to Buy and Sell Stock IV": ["2d-dp"],
    "Triangle": ["2d-dp"],
    # Greedy
    "Assign Cookies": ["greedy", "sorting"],
    "Can Place Flowers": ["greedy"],
    "Hand of Straights": ["greedy", "hashmap"],
    "Merge Triplets to Form Target Triplet": ["greedy"],
    "Partition Labels": ["greedy", "hashmap"],
    "Valid Parenthesis String": ["greedy"],
    # Intervals
    "Merge Intervals": ["intervals", "sorting"],
    "Insert Interval": ["intervals"],
    "Non-overlapping Intervals": ["intervals", "greedy", "sorting"],
    "Meeting Rooms": ["intervals", "sorting"],
    "Meeting Rooms II": ["intervals", "heap", "sorting"],
    "Minimum Number of Arrows to Burst Balloons": ["intervals", "greedy", "sorting"],
    "Minimum Interval to Include Each Query": ["intervals", "heap", "sorting"],
    "Summary Ranges": ["array"],
    # Math & Geometry
    "Add Strings": ["math", "string"],
    "Multiply Strings": ["math", "string"],
    "Plus One": ["math", "array"],
    "Sqrt(x)": ["math", "binary-search"],
    "Pow(x n)": ["math", "divide-and-conquer"],
    "Palindrome Number": ["math"],
    "Reverse Integer": ["math"],
    "Excel Sheet Column Title": ["math"],
    "Excel Sheet Column Number": ["math"],
    "Factorial Trailing Zeroes": ["math"],
    "Base 7": ["math"],
    "Power of Three": ["math"],
    "Perfect Number": ["math"],
    "Fizz Buzz": ["math"],
    "Maximum Product of Three Numbers": ["math", "sorting"],
    "Range Addition II": ["math"],
    "Construct the Rectangle": ["math"],
    "Detect Squares": ["geometry", "hashmap"],
    "Max Points on a Line": ["geometry", "hashmap", "math"],
    # Bit Manipulation
    "Single Number": ["bit-manipulation"],
    "Number of 1 Bits": ["bit-manipulation"],
    "Counting Bits": ["bit-manipulation"],
    "Reverse Bits": ["bit-manipulation"],
    "Missing Number": ["bit-manipulation"],
    "Sum of Two Integers": ["bit-manipulation"],
    "Power of Two": ["bit-manipulation"],
    "Add Binary": ["bit-manipulation", "string"],
    "Number Complement": ["bit-manipulation"],
    "Single Number II": ["bit-manipulation"],
    "Bitwise AND of Numbers Range": ["bit-manipulation"],
    # Matrix
    "Set Matrix Zeroes": ["matrix"],
    "Spiral Matrix": ["matrix"],
    "Rotate Image": ["matrix"],
    "Valid Sudoku": ["matrix", "hashmap"],
    "Game of Life": ["matrix", "simulation"],
    "Reshape the Matrix": ["matrix"],
    # Stack
    "Valid Parentheses": ["stack"],
    "Min Stack": ["design", "stack"],
    "Evaluate Reverse Polish Notation": ["stack"],
    "Daily Temperatures": ["monotonic-stack"],
    "Car Fleet": ["monotonic-stack"],
    "Largest Rectangle in Histogram": ["monotonic-stack"],
    "Basic Calculator": ["stack"],
    "Simplify Path": ["stack"],
    "Next Greater Element I": ["monotonic-stack"],
    "Implement Queue using Stacks": ["stack", "design"],
    "Implement Stack using Queues": ["stack", "design"],
    # Design
    "LRU Cache": ["design", "linked-list", "hashmap"],
    "Design Twitter": ["design", "heap", "hashmap"],
    "Find Median from Data Stream": ["design", "heap"],
    "Serialize and Deserialize Binary Tree": ["design", "tree-bfs"],
    "Insert Delete GetRandom O(1)": ["design", "hashmap", "array"],
    "Time Based Key-Value Store": ["design", "binary-search", "hashmap"],
    # Divide & Conquer
    "Convert Sorted Array to Binary Search Tree": ["divide-and-conquer", "bst"],
    "Construct Quad Tree": ["divide-and-conquer", "tree-dfs"],
    "Sort List": ["divide-and-conquer", "linked-list", "merge-sort"],
}
